# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    # environment:
    #   - VITE_GOOGLE_MAPS_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - backend
