
GET http://localhost:8080/ride/1?driver_id=2
###

POST http://localhost:8080/ride/estimate
Content-Type: application/json

{
  "customer_id": "1",
  "origin": "Rua B, 123, São Paulo, SP",
  "destination": "Av. C, 1000, São Paulo, SP"
}

###

PATCH http://localhost:8080/ride/confirm
Content-Type: application/json

{
  "customer_id": "1",
  "origin": "Rua B, 123, São Paulo, SP",
  "destination": "Av. C, 1000, São Paulo, SP",
  "distance": 10,
  "duration": "10 minutos",
  "driver": {
    "id": 2,
    "name": "Motorista Teste"
  },
  "value": 10
}
###
